### ISSUE TITLE
With shardTestFiles browser windows are not being closed after tests are finished

### ISSUE THREAD

**Issue by natalya-semenova** [protractor-cucumber-framework/protractor-cucumber-framework#101]
With shardTestFiles: true browser windows are not being closed after tests are finished. Launcher says 'X instance(s) of WebDriver still running' and test run never completes.

Node Version: v8.4.0
Protractor Version: 5.1.2
Angular Version: 1.6.5
Browser(s): Chrome
Operating System and Version Linux (Fedora release 26) x86_64
Please find the protractor configuration file, relevant example test, output from running the test, steps to reproduce here: https://github.com/natalya-semenova/issues

The original issue was opened here: angular/protractor#4480

**Comment by darrinholst** [comment]
[v4.0.5](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/releases/tag/4.0.5) should fix this.

We needed a bit of a hack to get this to work with cucumber 3.0.0 that relied on a relative tempfile since cucumber formatters with absolute paths didn't work at the time. The name that I used didn't change between shards so the browsers were locked waiting to cleanup the file. That was [fixed](https://github.com/cucumber/cucumber-js/pull/906) with 3.0.1 so we can use system temp files now.

**Comment by wswebcreation** [comment]
You are awesome

Gonna test it tonight!

**Comment by pawelus** [comment]
@darrinholst would it be possible to get a 1.x or 2.x release with this? I'd gladly use in our project as we can't use 4.x yet because of the problems sescribed in #100

**Comment by darrinholst** [comment]
The [bug that was introduced](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/index.js#L37-L43) and fixed for this issue was specifically for cucumber 3 support. If you're using 2.x then you're not using cucumber 3 so it should have never applied to you.

**Comment by wswebcreation** [comment]
@darrinholst 

Just did a verification and you fixed it, thanks!
