### ISSUE TITLE
shardTestFiles doesnt respect scenarios tags

### ISSUE THREAD

**Issue by gd46** [protractor-cucumber-framework/protractor-cucumber-framework#104]
shardTestFiles doesnt respect scenarios tags. So if I were to have the following: 

```
Feature: Example 1

    @example
   Scenario: Example scenario 1

Feature: Example 2
   
   @example2
   Scenario: Example scenario 2
```

If you were to use shardTestFiles true and run only @example tag you will notice that the browser will run both features even though only one feature has @example tag. Id like for shardTestFiles to respect tags so I can run features using sharding techniques. 

It would be nice to know how to get features and scenarios that meet tag criteria and feed it to protractor as shards so that the way sharding is handled could be more customizable. Not sure how to grab features that match the criteria I want. Any help is appreciated, thanks!

**Comment by darrinholst** [comment]
I setup an example of this [here](https://github.com/dholst/protractor-cucumber-framework-example/tree/sharded). You'll see that there are 3 feature files with 1 scenario tagged with `@example`. Protractor does indeed execute 3 times for the 3 feature files since it shards by file, but you'll see that only the 1 tagged scenario was run...

```
[08:41:46] I/launcher - Running 1 instances of WebDriver
[08:41:49] I/testLogger -
------------------------------------

[08:41:49] I/testLogger - [chrome #01-0] PID: 24299
[chrome #01-0] Specs: /Users/darrinholst/Projects/protractor-cucumber-framework-example/features/another-example.feature
[chrome #01-0]
[chrome #01-0] (node:24299) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #01-0] [08:41:47] I/local - Starting selenium standalone server...
[chrome #01-0] [08:41:47] I/local - Selenium standalone server started at http://192.168.0.7:61041/wd/hub
[chrome #01-0]
[chrome #01-0]
[chrome #01-0] 0 scenarios
[chrome #01-0] 0 steps
[chrome #01-0] 0m00.000s
[chrome #01-0] [08:41:49] I/local - Shutting down selenium standalone server.

[08:41:49] I/testLogger -

[08:41:49] I/launcher - 1 instance(s) of WebDriver still running
..[08:41:54] I/testLogger -
------------------------------------

[08:41:54] I/testLogger - [chrome #01-1] PID: 24319
[chrome #01-1] Specs: /Users/darrinholst/Projects/protractor-cucumber-framework-example/features/example.feature
[chrome #01-1]
[chrome #01-1] (node:24319) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #01-1] [08:41:49] I/local - Starting selenium standalone server...
[chrome #01-1] [08:41:50] I/local - Selenium standalone server started at http://192.168.0.7:59364/wd/hub
[chrome #01-1] ..
[chrome #01-1]
[chrome #01-1] 1 scenario (1 passed)
[chrome #01-1] 2 steps (2 passed)
[chrome #01-1] 0m02.615s
[chrome #01-1] [08:41:53] I/local - Shutting down selenium standalone server.

[08:41:54] I/testLogger -

[08:41:54] I/launcher - 1 instance(s) of WebDriver still running
[08:41:56] I/testLogger -
------------------------------------

[08:41:56] I/testLogger - [chrome #01-2] PID: 24339
[chrome #01-2] Specs: /Users/darrinholst/Projects/protractor-cucumber-framework-example/features/third-example.feature
[chrome #01-2]
[chrome #01-2] (node:24339) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #01-2] [08:41:54] I/local - Starting selenium standalone server...
[chrome #01-2] [08:41:55] I/local - Selenium standalone server started at http://192.168.0.7:56422/wd/hub
[chrome #01-2]
[chrome #01-2]
[chrome #01-2] 0 scenarios
[chrome #01-2] 0 steps
[chrome #01-2] 0m00.000s
[chrome #01-2] [08:41:56] I/local - Shutting down selenium standalone server.

[08:41:56] I/testLogger -

[08:41:56] I/launcher - 0 instance(s) of WebDriver still running
[08:41:56] I/launcher - chrome #01-0 passed
[08:41:56] I/launcher - chrome #01-1 passed
[08:41:56] I/launcher - chrome #01-2 passed
~
```

The problem is that protractor doesn't provide any way to customize how sharding is done (that I know of anyway). It just gets a list of files to run and splits them up equally. There is nothing that this library can do at the point it has control of anything. The only thing you could do is customize the list of specs that get run that is passed to protractor. I've done this before by getting a list of all scenarios (with line numbers) and passing that in as `multiCapabilities` (to avoid the overhead of new processes being created by `shardTestFiles`. That way the shards are more balanced in the number of scenarios that they run. An example of that is [here](https://gist.github.com/darrinholst/bd00aa0f40d5978a84c47b012215b080).

I could see a utility library being created to help with this if someone is inclined to build it, but this library isn't capable of doing it since it is just the glue between protractor and cucumber.

**Comment by gd46** [comment]
Hi @darrinholst I have tried your code sample with the latest protractor, and cucumber. When I kick off the tests I get two browsers open but no tests start running. It hangs on launching the browsers. Any thoughts?

**Comment by gd46** [comment]
I get it to launch if I copy my cucumberOpts from my original config. But then It opens two browsers and runs the same tests.

**Comment by darrinholst** [comment]
What version of protractor-cucumber-framework? Only 1 browser should open since `maxInstances` defaults to 1. Here are the versions that I'm working with and it's working as expected...

```
✓ npm list | grep -G "protractor\|cucumber"
protractor-cucumber-framework-example@1.0.0 /Users/darrinholst/Projects/protractor-cucumber-framework-example
├─┬ cucumber@3.0.2
│ ├─┬ cucumber-expressions@4.0.3
│ ├── cucumber-tag-expressions@1.0.1
├─┬ protractor@5.1.2
└─┬ protractor-cucumber-framework@4.0.8
~
```

![pcf](https://user-images.githubusercontent.com/4854/30814807-d0bd6546-a1d6-11e7-9e3a-5f465043bd57.gif)

**Comment by Xotabu4** [comment]
Maybe we should create this bug in protractor repo?

**Comment by Izhaki** [comment]
Here's a more up to date example of how to get this working:

https://github.com/gd46/dibellag-automation-framework/blob/master/configuration.js

I have to change a few things (eg, add `order: 'defined'` to the `getTestCasesFromFilesystem` call), but it did work eventually.
