### ISSUE TITLE
Error in path calculation with folders that have full stops in their name.

### ISSUE THREAD

**Issue by GWillits** [protractor-cucumber-framework/protractor-cucumber-framework#110]
This is a follow on issue from #109 
I'm afraid this has created a new problem with the path. Now it concats the original path with another causing an error. What I'm seeing in two different environments is:
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\development\git-svn\iViewPlus.External.Web.v2\node_modules\protractor-cucumber-framework\lib\resultsCap
turer.js:C:\Users\{username}\AppData\Local\Temp\tmp-3428lU76DQekkAoi.tmp'

I redacted the username there btw.
I appreciate the speedy turn around with #109 . If you could take a look at this that would be great. Thanks Garry.

**Comment by darrinholst** [comment]
Ahhh...windows...that’s why I kept it that way. That path is correct. The problem is cucumber is splitting on the `:` and not taking in account the drive letters. Will have to 🤔 about this one.
		
		

		
	




On Tue, Oct 17, 2017 at 6:22 AM -0500, "GWillits" <notifications@github.com> wrote:












This is a follow on issue from #109

I'm afraid this has created a new problem with the path. Now it concats the original path with another causing an error. What I'm seeing in two different environments is:

Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\development\git-svn\iViewPlus.External.Web.v2
ode_modules\protractor-cucumber-framework\lib\resultsCap

turer.js:C:\Users{username}\AppData\Local\Temp\tmp-3428lU76DQekkAoi.tmp'


I redacted the username there btw.

I appreciate the speedy turn around with #109 . If you could take a look at this that would be great. Thanks Garry.

**Comment by darrinholst** [comment]
I opened this [pr](https://github.com/cucumber/cucumber-js/pull/954). Hopefully that will fix this for you.

**Comment by darrinholst** [comment]
@GWillits can you check if upgrading to cucumber 3.0.6 fixes this?

**Comment by GWillits** [comment]
Great thanks. Yes it works providing you are up to date with protractor-cucumber-framework (4.0.9)
Thanks again for the speedy response.

Garry Willits
Developer
Digital Delivery Centre
NHS Digital

garry.willits@nhs.net<mailto:garry.willits@nhs.net>
0113 3946536 (Office no.)

NHS Digital provides information and technology for better health and care.
Find out more about who we are and what we do at https://www.digital.nhs.uk/<https://mail.google.com/mail/ca/u/0/#m_6720886675204004824__top>
@NHSDigital<https://mail.google.com/mail/ca/u/0/#m_6720886675204004824__top>
enquiries@nhsdigital.nhs.uk<mailto:enquiries@nhsdigital.nhs.uk>
General enquiries: 0300 303 5678

NHS Digital is the new trading name
for the Health and Social Care
Information Centre (HSCIC).
We provide ‘Information and
Technology for better health and care’.
