### ISSUE TITLE
Path of report moved from being relative to npm to being relative to where the protractor config is

### ISSUE THREAD

**Issue by Zialus** [protractor-cucumber-framework/protractor-cucumber-framework#203]
Starting from version `8.0.0` the path of the generated report moved from being relative to where the npm script is being invoked from, to being relative to where the protractor config is stored.

Let's say I have my configuration as described in the README

```
cucumberOpts: {
  strict: true,
  'no-colors': true,
  format: ['progress', 'pretty:output.txt'],
  // ...
}
```

the file `output.txt` will be stored in the same path as the protractor config instead of being stored in the current path where i'm executing `npm run e2e` from.

**Comment by Zialus** [comment]
Just to give a bit more info:

With this change it's not possible to use [protractor-multiple-cucumber-html-reporter-plugin
](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin) anymore.

This change was introduced by @jan-molak in 1dd70a94c31c69e7d192d2ad8e3f45b004defbf0 but I'm not sure exactly where in particular. Is this something that can be reversed?

**Comment by jan-molak** [comment]
Hi @Zialus!

You're correct, this is by design. It seems reasonable to assume that when people specify relative paths in any config file, what they mean is that those paths should be relative to where they've specified them. You'll find the original discussion about this at serenity-js/serenity-js#632

Having said that, I fully appreciate that your preference might be different to that of the majority, so I'd like to propose some ideas you might want to try.

## Use `process.cwd()` 

The first solution would be to be more explicit about where you'd like the output file to end up by specifying a path relative to [`process.cwd()`](https://nodejs.org/docs/latest-v14.x/api/process.html#process_process_cwd):

```
cucumberOpts: {
  format: [ `pretty:${ process.cwd() }/output.txt` ],
  // ...
}
```

This approach is, in fact, very similar to what is suggested in the [`README`](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#usage) for the `require` option and should get your old setup working with `8.0.0`.

## Use Serenity reports instead

Since [`protractor-multiple-cucumber-html-reporter-plugin`](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin) has been [deprecated](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/tree/f4d30dd1622ff2c03fa4457373a77baa4e4b4995#important-news) and hasn't been maintained since May 2020, your second option would be to migrate to [Serenity reports](https://serenity-js.org/handbook/reporting/index.html):

![image](https://user-images.githubusercontent.com/1089173/113491655-61cc0f80-94ca-11eb-80b9-ac14041ce95c.png)

[See a demo report](https://serenity-js.github.io/serenity-js-cucumber-protractor-template/)

To do that, you'd need to install Serenity/JS modules (which are dependencies of this project too):
```
npm install --save-dev @serenity-js/{core,protractor,serenity-bdd}
```

Add `serenity-bdd update` as a `postinstall` script in your `package.json` (see the [boilerplate project](https://github.com/serenity-js/serenity-js-cucumber-protractor-template/blob/bf3cb55eabc6bf696d56654f46c22bbabc569298/package.json#L7)):

```
"postinstall": "serenity-bdd update",
```

Next, change your `protractor.conf.js` file as per the [Serenity/JS Handbook](https://serenity-js.org/handbook/integration/serenityjs-and-protractor.html#configuration):

```javascript
const { ArtifactArchiver } = require('@serenity-js/core');
const { SerenityBDDReporter } = require('@serenity-js/serenity-bdd');

exports.config = {

    framework:      'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    // or directly:
    // frameworkPath:  require.resolve('@serenity-js/protractor/adapter'),

    serenity: {
        crew: [
            new SerenityBDDReporter(),
            ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
        ]
    },

    specs: [ 'features/*.feature', ],
    cucumberOpts: {
      // ...
    },
```

When your tests finish executing, you'll have a set of `json` files under `./target/site/serenity` (one per scenario), which you can then convert into a HTML report by running:

```
serenity-bdd run
```

You can make that an npm script to keep it simple, see [the example](https://github.com/serenity-js/serenity-js-cucumber-protractor-template/blob/bf3cb55eabc6bf696d56654f46c22bbabc569298/package.json#L9-L13).

Hope this helps!

Jan

**Comment by Zialus** [comment]
@jan-molak thank you very much for the very detailed explanation! I'll be giving SerenityJS a try soon!
