### ISSUE TITLE
Report steps to protractor engine

### ISSUE THREAD

**Issue by segrey** [protractor-cucumber-framework/protractor-cucumber-framework#63]
Currently, only scenarios are reported to protractor engine via 'testPass' and 'testFail' events. It'd be nice to report steps to provide users with much more details.

This feature was originally requested in https://youtrack.jetbrains.com/issue/WEB-24165#comment=27-1736886.
>I would expect to see the steps in the tree as well.  I'm thinking a click would go to the step in the scenario, a shift+click or context menu would take you to the step code definition.

**Comment by darrinholst** [comment]
It's easy enough to report step results, but I'm not seeing any documentation on what to send to protractor besides `testPass` and `testFail` [here](https://github.com/angular/protractor/blob/master/lib/frameworks/README.md#requirements). Is there any documentation out there anywhere?

**Comment by darrinholst** [comment]
Ahhh, I figured out what you were talking about. Instead of reporting the scenario as the test unit, we report the step now. This makes more sense...

<img width="509" alt="protractor_conf_js_-_retirement-nextgen_-____projects_retirement-nextgen_" src="https://cloud.githubusercontent.com/assets/4854/24874012/bc602ace-1de8-11e7-8d66-ca51cc8ac813.png">

This is available in v3.0.0

**Comment by segrey** [comment]
Great, thank you!
